image: alpine

stages:
  - test
  - deploy

test:
    stage: test
    script:
        - ./bin/install.sh
        - composer install
        - vendor/phpunit/phpunit/phpunit --coverage-text --colors=never

deploy:
  stage: deploy
  variables:
    GITLAB_HOST: 'https://git.twogether.io'
  script:
    - 'apk add --no-cache curl'
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "$GITLAB_HOST/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
  rules:
    - if: '$CI_COMMIT_TAG'

